[modules]
uvsub_mstransform = false
deep_wsclean = false
pybdsf = false
timeseries_wsclean = false
lightcurve = true

[general]
casa_dir = /home/ocbl_ubuntu/bin/casa-6.7.0-31-py3.12.el8/bin/casa
split_scans = false
max_parallel_scans = 2
wsclean_path =/usr/bin/wsclean
preamble=

[uvsub]
input_ms =SGRB-selfcal5.ms 

[mstransform]
scan =                                    
output_ms =

[wsclean_deep]
ms = 
output_prefix =
size = 8000,8000
scale = 1.5asec
channels-out = 2
wstack-kernel-size = 7
wstack-oversampling = 63
pol = I
data-column = DATA
niter = 10
auto-mask = 5
auto-threshold = 3
gain = 0.1
mgain = 0.7
multiscale-scale-bias = 0.6
fit-spectral-pol = 3
padding = 1.3
parallel-deconvolution = 8192

[pybdsf]
fits_image = 

[wsclean_timeseries]
ms = 
name =
size = 8000,8000
scale = 1.5asec
channels-out = 2
wstack-kernel-size = 7
wstack-oversampling = 63
pol = I
data-column = DATA
niter = 10
auto-mask = 5
auto-threshold = 3
gain = 0.1
mgain = 0.7
multiscale-scale-bias = 0.6
fit-spectral-pol = 3
padding = 1.3
parallel-deconvolution = 8192
time_interval = 35
scan = 

[lightcurve]
input_dir = lpt_images_1

# Required: RMS region coordinates (should match your image center or offset)
rms_ra_deg = 
rms_dec_deg = 
rms_radius_pix = 400

# Required: Filter bank (minutes)
filter_bank = auto

# Required: Detection threshold
SNR_threshold = 10.0

# Optional: Custom paths (leave empty for auto-search)
catalog_file = 
image_template = 

# Optional: Output directories
output_dir = lightcurve_output_lpt
transient_plot_dir = transient_plots_lpt

[lombscargle]
concatenate = false

# Path to CSV produced by lightcurve.py
# Leave empty to auto-detect from lightcurve output_dir
lightcurve_csv = 

# Minimum number of valid points for LS
min_points = 5

# Output directory for Lomb–Scargle results
output_dir = lombscargle_analysis

# Create periodogram plots
create_plots = true

[concatenate_catalogs]
concatenate = false
output_dir = concatenated_lightcurves
window_size = 31
k_sigma = 3.0
min_points = 3

[file_cleanup]
delete_files = split_ms/scan7/*.tmp, 

